// ============================================================================
// NEXUS ROYALE 2030 - OFFICIAL SUPERCELL HEROES & CARDS DATABASE (2026)
// Season 87 Meta: Featuring Hero Ice Wizard, 17 Official Heroes & 8 Champions
// ============================================================================

const CLASH_MECHANICS_2026 = {
  "systemName": "Clash Royale Heroes & 3-Slot Special System (2026)",
  "season": "Season 87 (September 2026)",
  "latestHero": "Hero Ice Wizard",
  "featureRarityExplanation": "Heroes are a Feature Rarity unlocked at Arena 5. Any regular base card placed into a dedicated Hero Slot transforms into a Hero with unique battle-ready manual abilities and golden crown auras.",
  "economy": {
    "currency": "Hero Coins",
    "cap": 200,
    "overflow": "1:1 Gem Conversion",
    "unlockCost": "100-200 Hero Coins (Deterministic unlock)"
  },
  "specialSlots": [
    {
      "slot": 1,
      "name": "Evolution Slot",
      "color": "#a855f7",
      "desc": "Exclusive to Evolution Cards."
    },
    {
      "slot": 2,
      "name": "Hero Slot",
      "color": "#eab308",
      "desc": "Exclusive to Heroes (Base cards imbued with abilities)."
    },
    {
      "slot": 3,
      "name": "Wild Slot",
      "color": "#06b6d4",
      "desc": "Flexible slot: hosts either a 2nd Evolution OR a 2nd Hero/Champion."
    }
  ],
  "balancePatch": {
    "date": "September 16, 2026",
    "title": "Emergency Balance Update & Princess Gambit Meta",
    "rule": "Hero Ice Wizard freeze reduced from 7s to 5s. Fireball crown tower damage nerfed (-8%). Base Wizard receives +8% damage buff. Poison tick damage fixed. Boss Bandit remains the single multi-use cooldown exception."
  }
};

const CLASH_CARDS = [
  {
    "id": 26000000,
    "name": "Knight",
    "key": "knight",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Iron Bulwark",
      "elixir": 1,
      "singleUse": true,
      "description": "Slams shield into the arena dirt, taunting all nearby enemy units to attack him while reducing all incoming damage by 70% for 4 seconds.",
      "badge": "S-TIER HERO",
      "proTip": "Activate when enemy Pekka, Sparky, or Mega Knight approaches to absorb high burst damage for only 1 elixir."
    }
  },
  {
    "id": 26000001,
    "name": "Archers",
    "key": "archers",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/W4Hmp8MTSdXANN8KdblbtHwtsbt0o749BbxNqmJYfA8.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/W4Hmp8MTSdXANN8KdblbtHwtsbt0o749BbxNqmJYfA8.png",
    "heroIcon": ""
  },
  {
    "id": 26000002,
    "name": "Goblins",
    "key": "goblins",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Gold Rush Decoy",
      "elixir": 1,
      "singleUse": true,
      "description": "Scatters glistening gold coins that distract non-building targeting enemy units for 2 seconds while dealing critical backstabs.",
      "badge": "B-TIER HERO",
      "proTip": "Stalls high single-target hitters like Bandit or Lumberjack while tower locks on."
    }
  },
  {
    "id": 26000003,
    "name": "Giant",
    "key": "giant",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Colossal Slam",
      "elixir": 2,
      "singleUse": true,
      "description": "Slams both fists into the arena, dealing shockwave area damage and stunning nearby defensive towers for 1.8s.",
      "badge": "B-TIER HERO",
      "proTip": "Stuns Inferno Tower right before it ramps up to max damage beam."
    }
  },
  {
    "id": 26000004,
    "name": "P.E.K.K.A",
    "key": "pekka",
    "elixir": 7,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/MlArURKhn_zWAZY-Xj1qIRKLVKquarG25BXDjUQajNs.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/MlArURKhn_zWAZY-Xj1qIRKLVKquarG25BXDjUQajNs.png",
    "heroIcon": ""
  },
  {
    "id": 26000005,
    "name": "Minions",
    "key": "minions",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/yHGpoEnmUWPGV_hBbhn-Kk-Bs838OjGzWzJJlQpQKQA.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000006,
    "name": "Balloon",
    "key": "balloon",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Propeller Overdrive",
      "elixir": 1,
      "singleUse": true,
      "description": "Activates a nitro propeller that surges forward with +60% velocity straight to the nearest enemy building.",
      "badge": "A-TIER HERO",
      "proTip": "Bypasses slow defensive buildings like Inferno Tower when combined with Freeze or Arrows."
    }
  },
  {
    "id": 26000007,
    "name": "Witch",
    "key": "witch",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/cfwk1vzehVyHC-uloEIH6NOI0hOdofCutR5PyhIgO6w.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/cfwk1vzehVyHC-uloEIH6NOI0hOdofCutR5PyhIgO6w.png",
    "heroIcon": ""
  },
  {
    "id": 26000008,
    "name": "Barbarians",
    "key": "barbarians",
    "elixir": 5,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/TvJsuu2S4yhyk1jVYUAQwdKOnW4U77KuWWOTPOWnwfI.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/TvJsuu2S4yhyk1jVYUAQwdKOnW4U77KuWWOTPOWnwfI.png",
    "heroIcon": ""
  },
  {
    "id": 26000009,
    "name": "Golem",
    "key": "golem",
    "elixir": 8,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/npdmCnET7jmVjJvjJQkFnNSNnDxYHDBigbvIAloFMds.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000010,
    "name": "Skeletons",
    "key": "skeletons",
    "elixir": 1,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/oO7iKMU5m0cdxhYPZA3nWQiAUh2yoGgdThLWB1rVSec.png",
    "heroIcon": ""
  },
  {
    "id": 26000011,
    "name": "Valkyrie",
    "key": "valkyrie",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Cyclone Vortex",
      "elixir": 1,
      "singleUse": true,
      "description": "Spins into a raging vortex, vacuuming all ground units within 4 tiles to her axe and dealing continuous heavy spin DPS.",
      "badge": "S-TIER HERO",
      "proTip": "Counters Goblin Drills, Royal Hogs, and Graveyard perfectly by pulling the entire swarm into a single lethal spin."
    }
  },
  {
    "id": 26000012,
    "name": "Skeleton Army",
    "key": "skeleton-army",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/fAOToOi1pRy7svN2xQS6mDkhQw2pj9m_17FauaNqyl4.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/fAOToOi1pRy7svN2xQS6mDkhQw2pj9m_17FauaNqyl4.png",
    "heroIcon": ""
  },
  {
    "id": 26000013,
    "name": "Bomber",
    "key": "bomber",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/12n1CesxKIcqVYntjxcF36EFA-ONw7Z-DoL0_rQrbdo.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/12n1CesxKIcqVYntjxcF36EFA-ONw7Z-DoL0_rQrbdo.png",
    "heroIcon": ""
  },
  {
    "id": 26000014,
    "name": "Musketeer",
    "key": "musketeer",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Sniper Stance",
      "elixir": 1,
      "singleUse": true,
      "description": "Kneels into a fortified sniper stance, gaining +3 tiles of targeting range and +35% armor piercing damage.",
      "badge": "C-TIER HERO",
      "proTip": "Outranges X-Bow and Mortar placements from complete safety behind your king tower."
    }
  },
  {
    "id": 26000015,
    "name": "Baby Dragon",
    "key": "baby-dragon",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/cjC9n4AvEZJ3urkVh-rwBkJ-aRSsydIMqSAV48hAih0.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/cjC9n4AvEZJ3urkVh-rwBkJ-aRSsydIMqSAV48hAih0.png",
    "heroIcon": ""
  },
  {
    "id": 26000016,
    "name": "Prince",
    "key": "prince",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/3JntJV62aY0G1Qh6LIs-ek-0ayeYFY3VItpG7cb9I60.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000017,
    "name": "Wizard",
    "key": "wizard",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Pyromancer Nova",
      "elixir": 2,
      "singleUse": true,
      "description": "Detonates a volcanic ring of flame around his perimeter, scorching air and ground swarms with continuous burn ticks.",
      "badge": "A-TIER HERO",
      "proTip": "Destroys Minion Horde, Goblin Gang, and Lava Pups in a single fiery burst."
    }
  },
  {
    "id": 26000018,
    "name": "Mini P.E.K.K.A",
    "key": "mini-pekka",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Pancake Overdrive",
      "elixir": 1,
      "singleUse": true,
      "description": "Consumes energized pancakes to gain instant cleave damage on his next 2 sword strikes and +45% sprint speed.",
      "badge": "B-TIER HERO",
      "proTip": "Allows Mini Pekka to slice through Skeleton Army or Goblin swarms that usually counter him."
    }
  },
  {
    "id": 26000019,
    "name": "Spear Goblins",
    "key": "spear-goblins",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/FSDFotjaXidI4ku_WFpVCTWS1hKGnFh1sxX0lxM43_E.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000020,
    "name": "Giant Skeleton",
    "key": "giant-skeleton",
    "elixir": 6,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/0p0gd0XaVRu1Hb1iSG1hTYbz2AN6aEiZnhaAib5O8Z8.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000021,
    "name": "Hog Rider",
    "key": "hog-rider",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Ubu0oUl8tZkusnkZf8Xv9Vno5IO29Y-jbZ4fhoNJ5oc.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000022,
    "name": "Minion Horde",
    "key": "minion-horde",
    "elixir": 5,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Wyjq5l0IXHTkX9Rmpap6HaH08MvjbxFp1xBO9a47YSI.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/Wyjq5l0IXHTkX9Rmpap6HaH08MvjbxFp1xBO9a47YSI.png",
    "heroIcon": ""
  },
  {
    "id": 26000023,
    "name": "Ice Wizard",
    "key": "ice-wizard",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Frost Surge",
      "elixir": 1,
      "singleUse": true,
      "description": "Unleashes an instant 360-degree freezing blizzard nova that slows hit speed by 65% and freezes swarm units in place for 2.5 seconds.",
      "badge": "SEASON 87 HERO",
      "proTip": "Deploy behind tower to freeze Bridge Spam rushes or neutralize high-DPS pushes like Beatdown tanks."
    }
  },
  {
    "id": 26000024,
    "name": "Royal Giant",
    "key": "royal-giant",
    "elixir": 6,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/mnlRaNtmfpQx2e6mp70sLd0ND-pKPF70Cf87_agEKg4.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/mnlRaNtmfpQx2e6mp70sLd0ND-pKPF70Cf87_agEKg4.png",
    "heroIcon": ""
  },
  {
    "id": 26000025,
    "name": "Guards",
    "key": "guards",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/1ArKfLJxYo6_NU_S9cAeIrfbXqWH0oULVJXedxBXQlU.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000026,
    "name": "Princess",
    "key": "princess",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/bAwMcqp9EKVIKH3ZLm_m0MqZFSG72zG-vKxpx8aKoVs.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/bAwMcqp9EKVIKH3ZLm_m0MqZFSG72zG-vKxpx8aKoVs.png",
    "heroIcon": ""
  },
  {
    "id": 26000027,
    "name": "Dark Prince",
    "key": "dark-prince",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Shield Charge",
      "elixir": 1,
      "singleUse": true,
      "description": "Regenerates 50% of lost shield health and immediately re-engages full charge momentum.",
      "badge": "C-TIER HERO",
      "proTip": "Re-charges right through heavy spells like The Log or Zap."
    }
  },
  {
    "id": 26000028,
    "name": "Three Musketeers",
    "key": "three-musketeers",
    "elixir": 9,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/_J2GhbkX3vswaFk1wG-dopwiHyNc_YiPhwroiKF3Mek.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000029,
    "name": "Lava Hound",
    "key": "lava-hound",
    "elixir": 7,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/unicRQ975sBY2oLtfgZbAI56ZvaWz7azj-vXTLxc0r8.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000030,
    "name": "Ice Spirit",
    "key": "ice-spirit",
    "elixir": 1,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/lv1budiafU9XmSdrDkk0NYyqASAFYyZ06CPysXKZXlA.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/lv1budiafU9XmSdrDkk0NYyqASAFYyZ06CPysXKZXlA.png",
    "heroIcon": ""
  },
  {
    "id": 26000031,
    "name": "Fire Spirit",
    "key": "fire-spirit",
    "elixir": 1,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/16-BqusVvynIgYI8_Jci3LDC-r8AI_xaIYLgXqtlmS8.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000032,
    "name": "Miner",
    "key": "miner",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Y4yWvdwBCg2FpAZgs8T09Gy34WOwpLZW-ttL52Ae8NE.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000033,
    "name": "Sparky",
    "key": "sparky",
    "elixir": 6,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/2GKMkBrArZXgQxf2ygFjDs4VvGYPbx8F6Lj_68iVhIM.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000034,
    "name": "Bowler",
    "key": "bowler",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Boulder Barrage",
      "elixir": 2,
      "singleUse": true,
      "description": "Heaves an enormous spiked boulder that penetrates through all troops in a line, knocking back even heavy giants.",
      "badge": "A-TIER HERO",
      "proTip": "Use in overtime to push back giant pushes and reset charging Prince or Ram Rider."
    }
  },
  {
    "id": 26000035,
    "name": "Lumberjack",
    "key": "lumberjack",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/E6RWrnCuk13xMX5OE1EQtLEKTZQV6B78d00y8PlXt6Q.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/E6RWrnCuk13xMX5OE1EQtLEKTZQV6B78d00y8PlXt6Q.png",
    "heroIcon": ""
  },
  {
    "id": 26000036,
    "name": "Battle Ram",
    "key": "battle-ram",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/dyc50V2cplKi4H7pq1B3I36pl_sEH5DQrNHboS_dbbM.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/dyc50V2cplKi4H7pq1B3I36pl_sEH5DQrNHboS_dbbM.png",
    "heroIcon": ""
  },
  {
    "id": 26000037,
    "name": "Inferno Dragon",
    "key": "inferno-dragon",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/y5HDbKtTbWG6En6TGWU0xoVIGs1-iQpIP4HC-VM7u8A.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/y5HDbKtTbWG6En6TGWU0xoVIGs1-iQpIP4HC-VM7u8A.png",
    "heroIcon": ""
  },
  {
    "id": 26000038,
    "name": "Ice Golem",
    "key": "ice-golem",
    "elixir": 2,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Glacial Fortress",
      "elixir": 1,
      "singleUse": true,
      "description": "Firmly roots into the arena, creating an aura of frostbite that slows all attackers and taunts Crown Towers for 3.5s.",
      "badge": "A-TIER HERO",
      "proTip": "Ultimate kite tool: pull Pekka or Mega Knight to the opposite lane with unyielding aggression."
    }
  },
  {
    "id": 26000039,
    "name": "Mega Minion",
    "key": "mega-minion",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Armor Harden",
      "elixir": 1,
      "singleUse": true,
      "description": "Fortifies dark metal armor, becoming immune to spell knockback and reflecting 40% of projectile damage back to attackers for 3s.",
      "badge": "A-TIER HERO",
      "proTip": "Activate against Poison, Fireball, or Flying Machine to survive and wipe out support troops."
    }
  },
  {
    "id": 26000040,
    "name": "Dart Goblin",
    "key": "dart-goblin",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/BmpK3bqEAviflqHCdxxnfm-_l3pRPJw3qxHkwS55nCY.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/BmpK3bqEAviflqHCdxxnfm-_l3pRPJw3qxHkwS55nCY.png",
    "heroIcon": ""
  },
  {
    "id": 26000041,
    "name": "Goblin Gang",
    "key": "goblin-gang",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/NHflxzVAQT4oAz7eDfdueqpictb5vrWezn1nuqFhE4w.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000042,
    "name": "Electro Wizard",
    "key": "electro-wizard",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/RsFaHgB3w6vXsTjXdPr3x8l_GbV9TbOUCvIx07prbrQ.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000043,
    "name": "Elite Barbarians",
    "key": "elite-barbarians",
    "elixir": 6,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/C88C5JH_F3lLZj6K-tLcMo5DPjrFmvzIb1R2M6xCfTE.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/C88C5JH_F3lLZj6K-tLcMo5DPjrFmvzIb1R2M6xCfTE.png",
    "heroIcon": ""
  },
  {
    "id": 26000044,
    "name": "Hunter",
    "key": "hunter",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/VNabB1WKnYtYRSG7X_FZfnZjQDHTBs9A96OGMFmecrA.png",
    "heroIcon": ""
  },
  {
    "id": 26000045,
    "name": "Executioner",
    "key": "executioner",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/9XL5BP2mqzV8kza6KF8rOxrpCZTyuGLp2l413DTjEoM.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/9XL5BP2mqzV8kza6KF8rOxrpCZTyuGLp2l413DTjEoM.png",
    "heroIcon": ""
  },
  {
    "id": 26000046,
    "name": "Bandit",
    "key": "bandit",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/QWDdXMKJNpv0go-HYaWQWP6p8uIOHjqn-zX7G0p3DyM.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000047,
    "name": "Royal Recruits",
    "key": "royal-recruits",
    "elixir": 7,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/jcNyYGUiXXNz3kuz8NBkHNKNREQKraXlb_Ts7rhCIdM.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/jcNyYGUiXXNz3kuz8NBkHNKNREQKraXlb_Ts7rhCIdM.png",
    "heroIcon": ""
  },
  {
    "id": 26000048,
    "name": "Night Witch",
    "key": "night-witch",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/NpCrXDEDBBJgNv9QrBAcJmmMFbS7pe3KCY8xJ5VB18A.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000049,
    "name": "Bats",
    "key": "bats",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/EnIcvO21hxiNpoI-zO6MDjLmzwPbq8Z4JPo2OKoVUjU.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/EnIcvO21hxiNpoI-zO6MDjLmzwPbq8Z4JPo2OKoVUjU.png",
    "heroIcon": ""
  },
  {
    "id": 26000050,
    "name": "Royal Ghost",
    "key": "royal-ghost",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/3En2cz0ISQAaMTHY3hj3rTveFN2kJYq-H4VxvdJNvCM.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/3En2cz0ISQAaMTHY3hj3rTveFN2kJYq-H4VxvdJNvCM.png",
    "heroIcon": ""
  },
  {
    "id": 26000051,
    "name": "Ram Rider",
    "key": "ram-rider",
    "elixir": 5,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/QaJyerT7f7oMyZ3Fv1glKymtLSvx7YUXisAulxl7zRI.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000052,
    "name": "Zappies",
    "key": "zappies",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/QZfHRpLRmutZbCr5fpLnTpIp89vLI6NrAwzGZ8tHEc4.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000053,
    "name": "Rascals",
    "key": "rascals",
    "elixir": 5,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/KV48DfwVHKx9XCjzBdk3daT_Eb52Me4VgjVO7WctRc4.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000054,
    "name": "Cannon Cart",
    "key": "cannon-cart",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/aqwxRz8HXzqlMCO4WMXNA1txynjXTsLinknqsgZLbok.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000055,
    "name": "Mega Knight",
    "key": "mega-knight",
    "elixir": 7,
    "rarity": "legendary",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/O2NycChSNhn_UK9nqBXUhhC_lILkiANzPuJjtjoz0CE.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/O2NycChSNhn_UK9nqBXUhhC_lILkiANzPuJjtjoz0CE.png",
    "heroIcon": ""
  },
  {
    "id": 26000056,
    "name": "Skeleton Barrel",
    "key": "skeleton-barrel",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/vCB4DWCcrGbTkarjcOiVz4aNDx6GWLm0yUepg9E1MGo.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/vCB4DWCcrGbTkarjcOiVz4aNDx6GWLm0yUepg9E1MGo.png",
    "heroIcon": ""
  },
  {
    "id": 26000057,
    "name": "Flying Machine",
    "key": "flying-machine",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/hzKNE3QwFcrSrDDRuVW3QY_OnrDPijSiIp-PsWgFevE.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000058,
    "name": "Wall Breakers",
    "key": "wall-breakers",
    "elixir": 2,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/_xPphEfC8eEwFNrfU3cMQG9-f5JaLQ31ARCA7l3XtW4.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/_xPphEfC8eEwFNrfU3cMQG9-f5JaLQ31ARCA7l3XtW4.png",
    "heroIcon": ""
  },
  {
    "id": 26000059,
    "name": "Royal Hogs",
    "key": "royal-hogs",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/ASSQJG_MoVq9e81HZzo4bynMnyLNpNJMfSLb3hqydOw.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/ASSQJG_MoVq9e81HZzo4bynMnyLNpNJMfSLb3hqydOw.png",
    "heroIcon": ""
  },
  {
    "id": 26000060,
    "name": "Goblin Giant",
    "key": "goblin-giant",
    "elixir": 6,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/SoW16cY3jXBwaTDvb39DkqiVsoFVaDWbzf5QBYphJrY.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/SoW16cY3jXBwaTDvb39DkqiVsoFVaDWbzf5QBYphJrY.png",
    "heroIcon": ""
  },
  {
    "id": 26000061,
    "name": "Fisherman",
    "key": "fisherman",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/U2KZ3g0wyufcuA5P2Xrn3Z3lr1WiJmc5S0IWOZHgizQ.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000062,
    "name": "Magic Archer",
    "key": "magic-archer",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Astral Piercing",
      "elixir": 2,
      "singleUse": true,
      "description": "Channels ancestral focus to fire a piercing geometric energy arrow that travels infinitely across the arena.",
      "badge": "C-TIER HERO",
      "proTip": "Snipes crown towers from across the river through multiple defending troops."
    }
  },
  {
    "id": 26000063,
    "name": "Electro Dragon",
    "key": "electro-dragon",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/tN9h6lnMNPCNsx0LMFmvpHgznbDZ1fBRkx-C7UfNmfY.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/tN9h6lnMNPCNsx0LMFmvpHgznbDZ1fBRkx-C7UfNmfY.png",
    "heroIcon": ""
  },
  {
    "id": 26000064,
    "name": "Firecracker",
    "key": "firecracker",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/c1rL3LO1U2D9-TkeFfAC18gP3AO8ztSwrcHMZplwL2Q.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/c1rL3LO1U2D9-TkeFfAC18gP3AO8ztSwrcHMZplwL2Q.png",
    "heroIcon": ""
  },
  {
    "id": 26000065,
    "name": "Mighty Miner",
    "key": "mighty-miner",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/Cd9R56yraxTvJiD8xJ2qT2OdsHyh94FqOAarXpbyelo.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Explosive Escape",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Digs underground to burrow into the opposite arena lane while dropping a heavy time-delayed bomb.",
      "badge": "CHAMPION",
      "proTip": "Escape Swarms and bait opponent's defense to the wrong lane."
    }
  },
  {
    "id": 26000067,
    "name": "Elixir Golem",
    "key": "elixir-golem",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/puhMsZjCIqy21HW3hYxjrk_xt8NIPyFqjRy-BeLKZwo.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000068,
    "name": "Battle Healer",
    "key": "battle-healer",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/KdwXcoigS2Kg-cgA7BJJIANbUJG6SNgjetRQ-MegZ08.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000069,
    "name": "Skeleton King",
    "key": "skeleton-king",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/dCd69_wN9f8DxwuqOGtR4QgWhHIPIaTNxZ1e23RzAAc.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Soul Summon",
      "abilityElixir": 2,
      "singleUse": true,
      "description": "Consumes collected souls from fallen arena troops to summon an explosive swarm of up to 16 skeletons.",
      "badge": "CHAMPION",
      "proTip": "Wait until souls meter is fully charged to overwhelm single-target tank killers."
    }
  },
  {
    "id": 26000072,
    "name": "Archer Queen",
    "key": "archer-queen",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/p7OQmOAFTery7zCzlpDdm-LOD1kINTm42AwIHchZfWk.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Cloaking Device",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Becomes invisible to enemy troops and towers while unleashing rapid-fire explosive arrows with 200% attack speed.",
      "badge": "CHAMPION",
      "proTip": "Activate right as she reaches the bridge to take 75%+ of a Princess Tower completely solo."
    }
  },
  {
    "id": 26000074,
    "name": "Golden Knight",
    "key": "golden-knight",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/WJd207D0O1sN-l1FTb8P9KhYL2oF5jY26vRUfTUW3FQ.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Dashing Dash",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Sprints forward executing up to 10 rapid chain-dashes through enemy lines with invulnerability frames.",
      "badge": "CHAMPION",
      "proTip": "Chain dash through defensive swarms directly onto the Crown Tower."
    }
  },
  {
    "id": 26000077,
    "name": "Monk",
    "key": "monk",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/2onG4t4-CxqwFVZAn6zpWxFz3_mG2ksSj4Q7zldo1SM.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Pensive Protection",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Enters a meditative stance forming a deflection shield that repels all incoming projectiles and spells.",
      "badge": "CHAMPION",
      "proTip": "Reflects Rocket, Fireball, and Goblin Barrels back onto enemy towers for instant match-winning damage."
    }
  },
  {
    "id": 26000080,
    "name": "Skeleton Dragons",
    "key": "skeleton-dragons",
    "elixir": 4,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/qPOtg9uONh47_NLxGhhFc_ww9PlZ6z3Ry507q1NZUXs.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000083,
    "name": "Mother Witch",
    "key": "mother-witch",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/fO-Xah8XZkYKaSK9SCp3wnzwxtvIhun9NVY-zzte1Ng.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000084,
    "name": "Electro Spirit",
    "key": "electro-spirit",
    "elixir": 1,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/WKd4-IAFsgPpMo7dDi9sujmYjRhOMEWiE07OUJpvD9g.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000085,
    "name": "Electro Giant",
    "key": "electro-giant",
    "elixir": 7,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/_uChZkNHAMq6tPb3v6A49xinOe3CnhjstOhG6OZbPYc.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000087,
    "name": "Phoenix",
    "key": "phoenix",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/i0RoY1fs6ay7VAxyFEfZGIPnD002nAKcne9FtJsWBHM.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000093,
    "name": "Little Prince",
    "key": "little-prince",
    "elixir": 3,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/dY-gSseki6KBpkIG17safHH5YlB8SErFZO9OXbJxf9w.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Royal Rescue",
      "abilityElixir": 3,
      "singleUse": true,
      "description": "Summons the Guardian charging into the arena, knocking back all surrounding enemies and tanking damage.",
      "badge": "CHAMPION",
      "proTip": "Use as an emergency push-back against Balloon, Prince, or aggressive bridge cards."
    }
  },
  {
    "id": 26000095,
    "name": "Goblin Demolisher",
    "key": "goblin-demolisher",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/KVVOgdn40xasFLYuQv8Go_U_LCV7wSG9q9eE1H7f3Qk.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000096,
    "name": "Goblin Machine",
    "key": "goblin-machine",
    "elixir": 5,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/-iLlotr6GCFndL_1BSBqWBb6DnsHBhLerd5EblZDNfU.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000097,
    "name": "Suspicious Bush",
    "key": "suspicious-bush",
    "elixir": 2,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/vqTzGAjseQv9F5rf4tsFWeocvg0dyPw1j_nB1cmDZfI.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000099,
    "name": "Goblinstein",
    "key": "goblinstein",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/mQ20B49dXdk7Nv0lMdLw175M3YvkSpN6KNnho8UKBd8.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Lightning Tether",
      "abilityElixir": 2,
      "singleUse": true,
      "description": "Links Doctor and Monster with high-voltage electricity, continuously frying all enemy troops passing between them.",
      "badge": "CHAMPION",
      "proTip": "Position Doctor near river and Monster at tower to create an unavoidable electric kill zone."
    }
  },
  {
    "id": 26000101,
    "name": "Rune Giant",
    "key": "rune-giant",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/UogMnGHQXT-TOVXRxslKdAKXUPhqUvrD_hV9x8lbzdE.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000102,
    "name": "Berserker",
    "key": "berserker",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/NA6W8S1JBYBlOPwD3dNvJLFvVDKq-UuBs_J3i3ewLFI.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/NA6W8S1JBYBlOPwD3dNvJLFvVDKq-UuBs_J3i3ewLFI.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Blood Frenzy",
      "elixir": 1,
      "singleUse": true,
      "description": "Enters an enraged frenzy, increasing movement speed and hit speed by 80% as HP drops below 50%.",
      "badge": "A-TIER HERO",
      "proTip": "Time the ability activation right as he crosses the bridge or engages a mini tank to melt tower HP."
    }
  },
  {
    "id": 26000103,
    "name": "Boss Bandit",
    "key": "boss-bandit",
    "elixir": 6,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/nuceG9o7rAyvyc7D3sp2QSiRYtSOEgraq0NJkDf729s.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Shadow Dash",
      "abilityElixir": 1,
      "singleUse": false,
      "cooldown": 11,
      "description": "The ONLY exception to the August 26, 2026 single-use patch! Dashes invisibly chaining across multiple high-value targets on an 11s cooldown.",
      "badge": "CHAMPION EXCEPTION",
      "proTip": "Can trigger dash multiple times per deployment across both arena lanes."
    }
  },
  {
    "id": 26000106,
    "name": "Ronin",
    "key": "ronin",
    "elixir": 5,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/X0dTFs7OGUavreDEzOtYd_YNZ8Zly6qgAE-dd-bNfWU.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 26000107,
    "name": "Minion Giant",
    "key": "minion-giant",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/VRjL0yVLzrnoe-IBh2l2fDHDok0L-UoM9cG-X_8xbMk.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000000,
    "name": "Cannon",
    "key": "cannon",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/nZK1y-beLxO5vnlyUhK6-2zH2NzXJwqykcosqQ1cmZ8.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/nZK1y-beLxO5vnlyUhK6-2zH2NzXJwqykcosqQ1cmZ8.png",
    "heroIcon": ""
  },
  {
    "id": 27000001,
    "name": "Goblin Hut",
    "key": "goblin-hut",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/l8ZdzzNLcwB4u7ihGgxNFQOjCT_njFuAhZr7D6PRF7E.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000002,
    "name": "Mortar",
    "key": "mortar",
    "elixir": 4,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/lPOSw6H7YOHq2miSCrf7ZDL3ANjhJdPPDYOTujdNrVE.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/lPOSw6H7YOHq2miSCrf7ZDL3ANjhJdPPDYOTujdNrVE.png",
    "heroIcon": ""
  },
  {
    "id": 27000003,
    "name": "Inferno Tower",
    "key": "inferno-tower",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/GSHY_wrooMMLET6bG_WJB8redtwx66c4i80ipi4gYOM.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000004,
    "name": "Bomb Tower",
    "key": "bomb-tower",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/rirYRyHPc97emRjoH-c1O8uZCBzPVnToaGuNGusF3TQ.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000005,
    "name": "Barbarian Hut",
    "key": "barbarian-hut",
    "elixir": 6,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/ho0nOG2y3Ch86elHHcocQs8Fv_QNe0cFJ2CijsxABZA.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000006,
    "name": "Tesla",
    "key": "tesla",
    "elixir": 4,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/OiwnGrxFMNiHetYEerE-UZt0L_uYNzFY7qV_CA_OxR4.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/OiwnGrxFMNiHetYEerE-UZt0L_uYNzFY7qV_CA_OxR4.png",
    "heroIcon": ""
  },
  {
    "id": 27000007,
    "name": "Elixir Collector",
    "key": "elixir-collector",
    "elixir": 6,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/BGLo3Grsp81c72EpxLLk-Sofk3VY56zahnUNOv3JcT0.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000008,
    "name": "X-Bow",
    "key": "x-bow",
    "elixir": 6,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/zVQ9Hme1hlj9Dc6e1ORl9xWwglcSrP7ejow5mAhLUJc.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 27000009,
    "name": "Tombstone",
    "key": "tombstone",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Catacomb Surge",
      "elixir": 1,
      "singleUse": true,
      "description": "Excavates an instant defensive shock-wave that bursts 6 armored skeletons in a circular perimeter.",
      "badge": "B-TIER HERO",
      "proTip": "Instantly surrounds Hog Rider, Prince, or Ram Rider upon bridge drop."
    }
  },
  {
    "id": 27000010,
    "name": "Furnace",
    "key": "furnace",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/iqbDiG7yYRIzvCPXdt9zPb3IvMt7F7Gi4wIPnh2x4aI.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/iqbDiG7yYRIzvCPXdt9zPb3IvMt7F7Gi4wIPnh2x4aI.png",
    "heroIcon": ""
  },
  {
    "id": 27000012,
    "name": "Goblin Cage",
    "key": "goblin-cage",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/vD24bBgK4rSq7wx5QEbuqChtPMRFviL_ep76GwQw1yA.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/vD24bBgK4rSq7wx5QEbuqChtPMRFviL_ep76GwQw1yA.png",
    "heroIcon": ""
  },
  {
    "id": 27000013,
    "name": "Goblin Drill",
    "key": "goblin-drill",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/eN2TKUYbih-26yBi0xy5LVFOA0zDftgDqxxnVfdIg1o.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/eN2TKUYbih-26yBi0xy5LVFOA0zDftgDqxxnVfdIg1o.png",
    "heroIcon": ""
  },
  {
    "id": 28000000,
    "name": "Fireball",
    "key": "fireball",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/lZD9MILQv7O-P3XBr_xOLS5idwuz3_7Ws9G60U36yhc.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000001,
    "name": "Arrows",
    "key": "arrows",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Flsoci-Y6y8ZFVi5uRFTmgkPnCmMyMVrU7YmmuPvSBo.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000002,
    "name": "Rage",
    "key": "rage",
    "elixir": 2,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/bGP21OOmcpHMJ5ZA79bHVV2D-NzPtDkvBskCNJb7pg0.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000003,
    "name": "Rocket",
    "key": "rocket",
    "elixir": 6,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Ie07nQNK9CjhKOa4-arFAewi4EroqaA-86Xo7r5tx94.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000004,
    "name": "Goblin Barrel",
    "key": "goblin-barrel",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/CoZdp5PpsTH858l212lAMeJxVJ0zxv9V-f5xC8Bvj5g.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/CoZdp5PpsTH858l212lAMeJxVJ0zxv9V-f5xC8Bvj5g.png",
    "heroIcon": ""
  },
  {
    "id": 28000005,
    "name": "Freeze",
    "key": "freeze",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/I1M20_Zs_p_BS1NaNIVQjuMJkYI_1-ePtwYZahn0JXQ.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000006,
    "name": "Mirror",
    "key": "mirror",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/wC6Cm9rKLEOk72zTsukVwxewKIoO4ZcMJun54zCPWvA.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000007,
    "name": "Lightning",
    "key": "lightning",
    "elixir": 6,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/fpnESbYqe5GyZmaVVYe-SEu7tE0Kxh_HZyVigzvLjks.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000008,
    "name": "Zap",
    "key": "zap",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/7dxh2-yCBy1x44GrBaL29vjqnEEeJXHEAlsi5g6D1eY.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/7dxh2-yCBy1x44GrBaL29vjqnEEeJXHEAlsi5g6D1eY.png",
    "heroIcon": ""
  },
  {
    "id": 28000009,
    "name": "Poison",
    "key": "poison",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/98HDkG2189yOULcVG9jz2QbJKtfuhH21DIrIjkOjxI8.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000010,
    "name": "Graveyard",
    "key": "graveyard",
    "elixir": 5,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Icp8BIyyfBTj1ncCJS7mb82SY7TPV-MAE-J2L2R48DI.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000011,
    "name": "The Log",
    "key": "the-log",
    "elixir": 2,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/_iDwuDLexHPFZ_x4_a0eP-rxCS6vwWgTs6DLauwwoaY.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000012,
    "name": "Tornado",
    "key": "tornado",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/QJB-QK1QJHdw4hjpAwVSyZBozc2ZWAR9pQ-SMUyKaT0.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000013,
    "name": "Clone",
    "key": "clone",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/mHVCet-1TkwWq-pxVIU2ZWY9_2z7Z7wtP25ArEUsP_g.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000014,
    "name": "Earthquake",
    "key": "earthquake",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/XeQXcrUu59C52DslyZVwCnbi4yamID-WxfVZLShgZmE.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000015,
    "name": "Barbarian Barrel",
    "key": "barbarian-barrel",
    "elixir": 2,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Spike Roll",
      "elixir": 1,
      "singleUse": true,
      "description": "Deploys heavy steel spikes onto the barrel rolling 30% further and knocking back medium troops.",
      "badge": "B-TIER HERO",
      "proTip": "Knocks back Valkyrie and Dark Prince, granting the exiting Barbarian first strike."
    }
  },
  {
    "id": 28000016,
    "name": "Heal Spirit",
    "key": "heal-spirit",
    "elixir": 1,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/GITl06sa2nGRLPvboyXbGEv5E3I-wAwn1Eqa5esggbc.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000017,
    "name": "Giant Snowball",
    "key": "giant-snowball",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/7MaJLa6hK9WN2_VIshuh5DIDfGwm0wEv98gXtAxLDPs.png",
    "heroIcon": ""
  },
  {
    "id": 28000018,
    "name": "Royal Delivery",
    "key": "royal-delivery",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/LPg7AGjGI3_xmi7gLLgGC50yKM1jJ2teWkZfoHJcIZo.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000023,
    "name": "Void",
    "key": "void",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/BykyeWDqzn4PlHSszu3NbrXT1mHxW2EA8vHbQGR5LDE.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000024,
    "name": "Goblin Curse",
    "key": "goblin-curse",
    "elixir": 2,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/OQPfGgT5mHEUvPuKKt0plZT0PNtIjCqUgQ3Rm86dQ2k.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000025,
    "name": "Spirit Empress",
    "key": "spirit-empress",
    "elixir": 6,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/MWWBZqiQeRBXSqEITVMj46nO_uCIUsqBidvUw9K2twY.png",
    "evoIcon": "",
    "heroIcon": ""
  },
  {
    "id": 28000026,
    "name": "Vines",
    "key": "vines",
    "elixir": 3,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/V5sJlPuo2WBRtirJ1lGEPJA4NvQ0KPwFeMrpxLX5z_8.png",
    "evoIcon": "",
    "heroIcon": ""
  }
];

const HEROES_CATALOG = [
  {
    "id": 26000000,
    "name": "Knight",
    "key": "knight",
    "elixir": 3,
    "rarity": "common",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/jAj1Q5rclXxU9kVImGqSJxa4wEMfEhvwNQ_4jiGUuqg.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Iron Bulwark",
      "elixir": 1,
      "singleUse": true,
      "description": "Slams shield into the arena dirt, taunting all nearby enemy units to attack him while reducing all incoming damage by 70% for 4 seconds.",
      "badge": "S-TIER HERO",
      "proTip": "Activate when enemy Pekka, Sparky, or Mega Knight approaches to absorb high burst damage for only 1 elixir."
    }
  },
  {
    "id": 26000002,
    "name": "Goblins",
    "key": "goblins",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/X_DQUye_OaS3QN6VC9CPw05Fit7wvSm3XegXIXKP--0.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Gold Rush Decoy",
      "elixir": 1,
      "singleUse": true,
      "description": "Scatters glistening gold coins that distract non-building targeting enemy units for 2 seconds while dealing critical backstabs.",
      "badge": "B-TIER HERO",
      "proTip": "Stalls high single-target hitters like Bandit or Lumberjack while tower locks on."
    }
  },
  {
    "id": 26000003,
    "name": "Giant",
    "key": "giant",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Axr4ox5_b7edmLsoHxBX3vmgijAIibuF6RImTbqLlXE.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Colossal Slam",
      "elixir": 2,
      "singleUse": true,
      "description": "Slams both fists into the arena, dealing shockwave area damage and stunning nearby defensive towers for 1.8s.",
      "badge": "B-TIER HERO",
      "proTip": "Stuns Inferno Tower right before it ramps up to max damage beam."
    }
  },
  {
    "id": 26000006,
    "name": "Balloon",
    "key": "balloon",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/qBipxLo-3hhCnPrApp2Nn3b2NgrSrvwzWytvREev0CY.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Propeller Overdrive",
      "elixir": 1,
      "singleUse": true,
      "description": "Activates a nitro propeller that surges forward with +60% velocity straight to the nearest enemy building.",
      "badge": "A-TIER HERO",
      "proTip": "Bypasses slow defensive buildings like Inferno Tower when combined with Freeze or Arrows."
    }
  },
  {
    "id": 26000011,
    "name": "Valkyrie",
    "key": "valkyrie",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/0lIoYf3Y_plFTzo95zZL93JVxpfb3MMgFDDhgSDGU9A.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Cyclone Vortex",
      "elixir": 1,
      "singleUse": true,
      "description": "Spins into a raging vortex, vacuuming all ground units within 4 tiles to her axe and dealing continuous heavy spin DPS.",
      "badge": "S-TIER HERO",
      "proTip": "Counters Goblin Drills, Royal Hogs, and Graveyard perfectly by pulling the entire swarm into a single lethal spin."
    }
  },
  {
    "id": 26000014,
    "name": "Musketeer",
    "key": "musketeer",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Tex1C48UTq9FKtAX-3tzG0FJmc9jzncUZG3bb5Vf-Ds.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Sniper Stance",
      "elixir": 1,
      "singleUse": true,
      "description": "Kneels into a fortified sniper stance, gaining +3 tiles of targeting range and +35% armor piercing damage.",
      "badge": "C-TIER HERO",
      "proTip": "Outranges X-Bow and Mortar placements from complete safety behind your king tower."
    }
  },
  {
    "id": 26000017,
    "name": "Wizard",
    "key": "wizard",
    "elixir": 5,
    "rarity": "rare",
    "hasEvolution": true,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "evoIcon": "https://api-assets.clashroyale.com/cardevolutions/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Mej7vnv4H_3p_8qPs_N6_GKahy6HDr7pU7i9eTHS84U.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Pyromancer Nova",
      "elixir": 2,
      "singleUse": true,
      "description": "Detonates a volcanic ring of flame around his perimeter, scorching air and ground swarms with continuous burn ticks.",
      "badge": "A-TIER HERO",
      "proTip": "Destroys Minion Horde, Goblin Gang, and Lava Pups in a single fiery burst."
    }
  },
  {
    "id": 26000018,
    "name": "Mini P.E.K.K.A",
    "key": "mini-pekka",
    "elixir": 4,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Fmltc4j3Ve9vO_xhHHPEO3PRP3SmU2oKp2zkZQHRZT4.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Pancake Overdrive",
      "elixir": 1,
      "singleUse": true,
      "description": "Consumes energized pancakes to gain instant cleave damage on his next 2 sword strikes and +45% sprint speed.",
      "badge": "B-TIER HERO",
      "proTip": "Allows Mini Pekka to slice through Skeleton Army or Goblin swarms that usually counter him."
    }
  },
  {
    "id": 26000023,
    "name": "Ice Wizard",
    "key": "ice-wizard",
    "elixir": 3,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/W3dkw0HTw9n1jB-zbknY2w3wHuyuLxSRIAV5fUT1SEY.png",
    "heroTier": "S",
    "heroAbility": {
      "name": "Frost Surge",
      "elixir": 1,
      "singleUse": true,
      "description": "Unleashes an instant 360-degree freezing blizzard nova that slows hit speed by 65% and freezes swarm units in place for 2.5 seconds.",
      "badge": "SEASON 87 HERO",
      "proTip": "Deploy behind tower to freeze Bridge Spam rushes or neutralize high-DPS pushes like Beatdown tanks."
    }
  },
  {
    "id": 26000027,
    "name": "Dark Prince",
    "key": "dark-prince",
    "elixir": 4,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/M7fXlrKXHu2IvpSGpk36kXVstslbR08Bbxcy0jQcln8.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Shield Charge",
      "elixir": 1,
      "singleUse": true,
      "description": "Regenerates 50% of lost shield health and immediately re-engages full charge momentum.",
      "badge": "C-TIER HERO",
      "proTip": "Re-charges right through heavy spells like The Log or Zap."
    }
  },
  {
    "id": 26000034,
    "name": "Bowler",
    "key": "bowler",
    "elixir": 5,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/SU4qFXmbQXWjvASxVI6z9IJuTYolx4A0MKK90sTIE88.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Boulder Barrage",
      "elixir": 2,
      "singleUse": true,
      "description": "Heaves an enormous spiked boulder that penetrates through all troops in a line, knocking back even heavy giants.",
      "badge": "A-TIER HERO",
      "proTip": "Use in overtime to push back giant pushes and reset charging Prince or Ram Rider."
    }
  },
  {
    "id": 26000038,
    "name": "Ice Golem",
    "key": "ice-golem",
    "elixir": 2,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/r05cmpwV1o7i7FHodtZwW3fmjbXCW34IJCsDEV5cZC4.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Glacial Fortress",
      "elixir": 1,
      "singleUse": true,
      "description": "Firmly roots into the arena, creating an aura of frostbite that slows all attackers and taunts Crown Towers for 3.5s.",
      "badge": "A-TIER HERO",
      "proTip": "Ultimate kite tool: pull Pekka or Mega Knight to the opposite lane with unyielding aggression."
    }
  },
  {
    "id": 26000039,
    "name": "Mega Minion",
    "key": "mega-minion",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/-T_e4YLbuhPBKbYnBwQfXgynNpp5eOIN_0RracYwL9c.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Armor Harden",
      "elixir": 1,
      "singleUse": true,
      "description": "Fortifies dark metal armor, becoming immune to spell knockback and reflecting 40% of projectile damage back to attackers for 3s.",
      "badge": "A-TIER HERO",
      "proTip": "Activate against Poison, Fireball, or Flying Machine to survive and wipe out support troops."
    }
  },
  {
    "id": 26000062,
    "name": "Magic Archer",
    "key": "magic-archer",
    "elixir": 4,
    "rarity": "legendary",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Avli3W7BxU9HQ2SoLiXnBgGx25FoNXUSFm7OcAk68ek.png",
    "heroTier": "C",
    "heroAbility": {
      "name": "Astral Piercing",
      "elixir": 2,
      "singleUse": true,
      "description": "Channels ancestral focus to fire a piercing geometric energy arrow that travels infinitely across the arena.",
      "badge": "C-TIER HERO",
      "proTip": "Snipes crown towers from across the river through multiple defending troops."
    }
  },
  {
    "id": 26000065,
    "name": "Mighty Miner",
    "key": "mighty-miner",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/Cd9R56yraxTvJiD8xJ2qT2OdsHyh94FqOAarXpbyelo.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Explosive Escape",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Digs underground to burrow into the opposite arena lane while dropping a heavy time-delayed bomb.",
      "badge": "CHAMPION",
      "proTip": "Escape Swarms and bait opponent's defense to the wrong lane."
    }
  },
  {
    "id": 26000069,
    "name": "Skeleton King",
    "key": "skeleton-king",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/dCd69_wN9f8DxwuqOGtR4QgWhHIPIaTNxZ1e23RzAAc.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Soul Summon",
      "abilityElixir": 2,
      "singleUse": true,
      "description": "Consumes collected souls from fallen arena troops to summon an explosive swarm of up to 16 skeletons.",
      "badge": "CHAMPION",
      "proTip": "Wait until souls meter is fully charged to overwhelm single-target tank killers."
    }
  },
  {
    "id": 26000072,
    "name": "Archer Queen",
    "key": "archer-queen",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/p7OQmOAFTery7zCzlpDdm-LOD1kINTm42AwIHchZfWk.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Cloaking Device",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Becomes invisible to enemy troops and towers while unleashing rapid-fire explosive arrows with 200% attack speed.",
      "badge": "CHAMPION",
      "proTip": "Activate right as she reaches the bridge to take 75%+ of a Princess Tower completely solo."
    }
  },
  {
    "id": 26000074,
    "name": "Golden Knight",
    "key": "golden-knight",
    "elixir": 4,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/WJd207D0O1sN-l1FTb8P9KhYL2oF5jY26vRUfTUW3FQ.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Dashing Dash",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Sprints forward executing up to 10 rapid chain-dashes through enemy lines with invulnerability frames.",
      "badge": "CHAMPION",
      "proTip": "Chain dash through defensive swarms directly onto the Crown Tower."
    }
  },
  {
    "id": 26000077,
    "name": "Monk",
    "key": "monk",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/2onG4t4-CxqwFVZAn6zpWxFz3_mG2ksSj4Q7zldo1SM.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Pensive Protection",
      "abilityElixir": 1,
      "singleUse": true,
      "description": "Enters a meditative stance forming a deflection shield that repels all incoming projectiles and spells.",
      "badge": "CHAMPION",
      "proTip": "Reflects Rocket, Fireball, and Goblin Barrels back onto enemy towers for instant match-winning damage."
    }
  },
  {
    "id": 26000093,
    "name": "Little Prince",
    "key": "little-prince",
    "elixir": 3,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/dY-gSseki6KBpkIG17safHH5YlB8SErFZO9OXbJxf9w.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Royal Rescue",
      "abilityElixir": 3,
      "singleUse": true,
      "description": "Summons the Guardian charging into the arena, knocking back all surrounding enemies and tanking damage.",
      "badge": "CHAMPION",
      "proTip": "Use as an emergency push-back against Balloon, Prince, or aggressive bridge cards."
    }
  },
  {
    "id": 26000099,
    "name": "Goblinstein",
    "key": "goblinstein",
    "elixir": 5,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/mQ20B49dXdk7Nv0lMdLw175M3YvkSpN6KNnho8UKBd8.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Lightning Tether",
      "abilityElixir": 2,
      "singleUse": true,
      "description": "Links Doctor and Monster with high-voltage electricity, continuously frying all enemy troops passing between them.",
      "badge": "CHAMPION",
      "proTip": "Position Doctor near river and Monster at tower to create an unavoidable electric kill zone."
    }
  },
  {
    "id": 26000102,
    "name": "Berserker",
    "key": "berserker",
    "elixir": 2,
    "rarity": "common",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/NA6W8S1JBYBlOPwD3dNvJLFvVDKq-UuBs_J3i3ewLFI.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/NA6W8S1JBYBlOPwD3dNvJLFvVDKq-UuBs_J3i3ewLFI.png",
    "heroTier": "A",
    "heroAbility": {
      "name": "Blood Frenzy",
      "elixir": 1,
      "singleUse": true,
      "description": "Enters an enraged frenzy, increasing movement speed and hit speed by 80% as HP drops below 50%.",
      "badge": "A-TIER HERO",
      "proTip": "Time the ability activation right as he crosses the bridge or engages a mini tank to melt tower HP."
    }
  },
  {
    "id": 26000103,
    "name": "Boss Bandit",
    "key": "boss-bandit",
    "elixir": 6,
    "rarity": "champion",
    "hasEvolution": false,
    "hasHero": false,
    "isChampion": true,
    "icon": "https://api-assets.clashroyale.com/cards/300/nuceG9o7rAyvyc7D3sp2QSiRYtSOEgraq0NJkDf729s.png",
    "evoIcon": "",
    "heroIcon": "",
    "championAbility": {
      "abilityName": "Shadow Dash",
      "abilityElixir": 1,
      "singleUse": false,
      "cooldown": 11,
      "description": "The ONLY exception to the August 26, 2026 single-use patch! Dashes invisibly chaining across multiple high-value targets on an 11s cooldown.",
      "badge": "CHAMPION EXCEPTION",
      "proTip": "Can trigger dash multiple times per deployment across both arena lanes."
    }
  },
  {
    "id": 27000009,
    "name": "Tombstone",
    "key": "tombstone",
    "elixir": 3,
    "rarity": "rare",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/LjSfSbwQfkZuRJY4pVxKspZ-a0iM5KAhU8w-a_N5Z7Y.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Catacomb Surge",
      "elixir": 1,
      "singleUse": true,
      "description": "Excavates an instant defensive shock-wave that bursts 6 armored skeletons in a circular perimeter.",
      "badge": "B-TIER HERO",
      "proTip": "Instantly surrounds Hog Rider, Prince, or Ram Rider upon bridge drop."
    }
  },
  {
    "id": 28000015,
    "name": "Barbarian Barrel",
    "key": "barbarian-barrel",
    "elixir": 2,
    "rarity": "epic",
    "hasEvolution": false,
    "hasHero": true,
    "isChampion": false,
    "icon": "https://api-assets.clashroyale.com/cards/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png",
    "evoIcon": "",
    "heroIcon": "https://api-assets.clashroyale.com/cardheroes/300/Gb0G1yNy0i5cIGUHin8uoFWxqntNtRPhY_jeMXg7HnA.png",
    "heroTier": "B",
    "heroAbility": {
      "name": "Spike Roll",
      "elixir": 1,
      "singleUse": true,
      "description": "Deploys heavy steel spikes onto the barrel rolling 30% further and knocking back medium troops.",
      "badge": "B-TIER HERO",
      "proTip": "Knocks back Valkyrie and Dark Prince, granting the exiting Barbarian first strike."
    }
  }
];

const PRO_META_DECKS = [
  {
    "id": "deck_hero_icewiz_pekka",
    "name": "Season 87 Hero Ice Wizard PEKKA Control (Post-Nerf)",
    "archetype": "Control / Anti-Meta",
    "tier": "S+",
    "winRate": 58.2,
    "useRate": 12.1,
    "threeCrownRate": 21.4,
    "avgElixir": 3.6,
    "proPlayer": "Mohamed Light",
    "rank": "#1 World Champion",
    "specialSlots": {
      "heroSlot": "ice-wizard",
      "evoSlot": "pekka",
      "wildSlot": "knight"
    },
    "cards": [
      "ice-wizard",
      "pekka",
      "knight",
      "zap",
      "poison",
      "electro-spirit",
      "bandit",
      "baby-dragon"
    ],
    "description": "Remains S+ tier after the Sept 16 emergency balance update. Despite Frost Surge freeze reduced to 5s, the 1-Elixir cost still provides unparalleled shutdown against beatdown, paired with Evo PEKKA and Wild Slot Hero Knight."
  },
  {
    "id": "deck_miner_poison_control",
    "name": "Miner Poison Cycle (Poison Fix Surge)",
    "archetype": "Control / Chip Siege",
    "tier": "S",
    "winRate": 57.8,
    "useRate": 11.5,
    "threeCrownRate": 12.2,
    "avgElixir": 2.9,
    "proPlayer": "LucasX-Gamer",
    "rank": "#2 Global Ultimate Champion",
    "specialSlots": {
      "heroSlot": "knight",
      "evoSlot": "skeletons",
      "wildSlot": "valkyrie"
    },
    "cards": [
      "miner",
      "poison",
      "knight",
      "skeletons",
      "musketeer",
      "the-log",
      "electro-spirit",
      "inferno-tower"
    ],
    "description": "Surged into the top ladder rankings following the Supercell bug fix ensuring Poison deals 100% intended tick damage. Grinds down crown towers while impenetrable ground defense handles beatdown."
  },
  {
    "id": "deck_princess_gambit_lumberloon",
    "name": "Princess Gambit Sudden Death LumberLoon Freeze",
    "archetype": "Sudden Death / Fast Punish",
    "tier": "S",
    "winRate": 59.4,
    "useRate": 14.8,
    "threeCrownRate": 92.0,
    "avgElixir": 3.8,
    "proPlayer": "Surgical Goblin",
    "rank": "Tournament Specialist",
    "specialSlots": {
      "heroSlot": "valkyrie",
      "evoSlot": "skeletons",
      "wildSlot": "ice-golem"
    },
    "cards": [
      "lumberjack",
      "balloon",
      "freeze",
      "bowler",
      "tornado",
      "electro-dragon",
      "barbarian-barrel",
      "ice-golem"
    ],
    "description": "The premier deck dominating the Princess Gambit Global Tournament (Sept 21–26). In Sudden Death format without a King Tower, a single Lumberjack + Balloon + Freeze drop cleanly secures the 1-tower victory."
  },
  {
    "id": "deck_giant_sparky_wizard",
    "name": "Giant Sparky Wizard Beatdown (Post-Buff)",
    "archetype": "Heavy Beatdown / Splash Overload",
    "tier": "S",
    "winRate": 56.9,
    "useRate": 8.7,
    "threeCrownRate": 34.5,
    "avgElixir": 3.9,
    "proPlayer": "Tobi SpiritHawk",
    "rank": "#5 Ultimate Champion",
    "specialSlots": {
      "heroSlot": "wizard",
      "evoSlot": "zap",
      "wildSlot": "dark-prince"
    },
    "cards": [
      "giant",
      "sparky",
      "wizard",
      "minion-giant",
      "zap",
      "tornado",
      "dark-prince",
      "mega-minion"
    ],
    "description": "Elevated directly by the September 16 patch granting Base Wizard +8% splash damage, shredding swarm defense while Sparky and the new Minion Giant melt defensive towers."
  },
  {
    "id": "deck_hog_26_postbalance",
    "name": "Hog 2.6 Cycle (Post-Balance Tuning)",
    "archetype": "Fast Cycle / Precision Defense",
    "tier": "S",
    "winRate": 56.4,
    "useRate": 13.2,
    "threeCrownRate": 10.1,
    "avgElixir": 2.6,
    "proPlayer": "Oyassuu",
    "rank": "#1 Global 2.6 Master",
    "specialSlots": {
      "heroSlot": "musketeer",
      "evoSlot": "skeletons",
      "wildSlot": "ice-golem"
    },
    "cards": [
      "hog-rider",
      "musketeer",
      "ice-golem",
      "cannon",
      "fireball",
      "the-log",
      "skeletons",
      "ice-spirit"
    ],
    "description": "The timeless standard remains resilient. Post-patch tactics utilize Ice Spirit strictly for defensive stalls rather than raw chip, offsetting the Fireball crown tower damage adjustment."
  },
  {
    "id": "deck_boss_bandit_bridge",
    "name": "Boss Bandit Overdrive Bridge Spam",
    "archetype": "Bridge Spam / Dual Lane",
    "tier": "S",
    "winRate": 56.1,
    "useRate": 9.3,
    "threeCrownRate": 23.5,
    "avgElixir": 3.5,
    "proPlayer": "Viper",
    "rank": "#3 Ultimate Champion",
    "specialSlots": {
      "heroSlot": "mega-minion",
      "evoSlot": "battle-ram",
      "wildSlot": "boss-bandit"
    },
    "cards": [
      "boss-bandit",
      "battle-ram",
      "mega-minion",
      "royal-ghost",
      "electro-wizard",
      "fireball",
      "the-log",
      "poison"
    ],
    "description": "Continues strong performance in competitive dual-lane pressure, relying on Boss Bandit's multi-use Dash cooldown to punish opponents after defending."
  }
];

const TOP_PRO_PLAYERS = [
  {
    "rank": 1,
    "name": "Mohamed Light",
    "tag": "#8UQP9G0",
    "trophies": 9000,
    "medals": 3480,
    "clan": "Twisted Minds",
    "winRate": "78.4%",
    "streak": 12,
    "favoriteHero": "Hero Ice Wizard",
    "activeDeck": "Hero Ice Wizard PEKKA Control"
  },
  {
    "rank": 2,
    "name": "Ryley",
    "tag": "#29009GL",
    "trophies": 9000,
    "medals": 3420,
    "clan": "SK Gaming",
    "winRate": "76.2%",
    "streak": 8,
    "favoriteHero": "Hero Knight",
    "activeDeck": "Hero Knight 2.8 Log Bait"
  },
  {
    "rank": 3,
    "name": "Viper",
    "tag": "#9R9UPGJCC",
    "trophies": 9000,
    "medals": 3390,
    "clan": "Natus Vincere",
    "winRate": "75.1%",
    "streak": 6,
    "favoriteHero": "Boss Bandit (Champion)",
    "activeDeck": "Boss Bandit Bridge Spam"
  },
  {
    "rank": 4,
    "name": "Ian77",
    "tag": "#GLUJCQ9L",
    "trophies": 9000,
    "medals": 3350,
    "clan": "Tribe Gaming",
    "winRate": "74.8%",
    "streak": 9,
    "favoriteHero": "Hero Valkyrie",
    "activeDeck": "Hero Valkyrie Hog EQ"
  }
];
